// vue-todo/client/App.vue
<template>
<div>
	<AddTodo :state="state" />
	<TodoList :state="state"/>
  	<Footer :state="state"  />
</div>

</template>
<script>
import Footer from "./Footer.vue";
import TodoList from "./TodoList.vue";
import AddTodo from "./AddTodo.vue";
export default {
	props: ["state"],
	components: {
		Footer,
		TodoList,
		AddTodo
	}
};
</script>

// react-todo/client/App.js
import React from "react";
import Footer from "./Footer";
import AddTodo from "./AddTodo";
import VisibleTodoList from "./VisibleTodoList";

const GState = require("../../../gstate");
const state = new GState();

const App = () => (
	<div>
		<AddTodo state={state} />
		<VisibleTodoList state={state} />
		<Footer state={state} />
	</div>
);

export default App;
