// react-todo/client/FilterLink.js
import React from "react";
import { setVisibilityFilter } from "./actions";
import Link from "./Link";
import gstate from "../../react-gstate";

const FilterLink = gstate(
	{
		filter: 1
	},
	(props, data = {}) => {
		return (
			<Link
				active={props.filter === data.filter}
				onClick={() => setVisibilityFilter(props.state, props.filter)}
				children={props.children}
			/>
		);
	}
);

export default FilterLink;

// vue-todo/client/FilterLink.vue
<template>
  	<Link :active="active" :onClick="onClick">
		<slot />  
	</Link>
</template>
<script>
import { setVisibilityFilter } from "./actions";
import Link from "./Link.vue";

export default {
	props: ["state", "filter"],
	gstate: {
		query: {
			filter: 1
		},
		data: {}
	},
	computed: {
		active() {
			return this.filter == this.$query.data.filter;
		}
	},
	methods: {
		onClick() {
			return setVisibilityFilter(this.state, this.filter);
		}
	},
	components: {
		Link
	}
};
</script>
